"""add blocos personalizados e anexos

Revision ID: 655b50076318
Revises: d196b0c7c507
Create Date: 2026-06-13 16:26:54.963552

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '655b50076318'
down_revision = 'd196b0c7c507'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blocos_personalizados',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('projeto_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('tipo_chave', sa.String(length=100), nullable=False),
    sa.Column('ordem', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['projeto_id'], ['projetos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('blocos_personalizados', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_blocos_personalizados_projeto_id'), ['projeto_id'], unique=False)

    op.create_table('anexos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('requisito_id', sa.Integer(), nullable=False),
    sa.Column('projeto_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('tipo_mime', sa.String(length=100), nullable=False),
    sa.Column('dados', sa.LargeBinary(), nullable=False),
    sa.Column('tamanho', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['projeto_id'], ['projetos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requisito_id'], ['requisitos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('anexos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_anexos_projeto_id'), ['projeto_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_anexos_requisito_id'), ['requisito_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('anexos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_anexos_requisito_id'))
        batch_op.drop_index(batch_op.f('ix_anexos_projeto_id'))

    op.drop_table('anexos')
    with op.batch_alter_table('blocos_personalizados', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_blocos_personalizados_projeto_id'))

    op.drop_table('blocos_personalizados')
    # ### end Alembic commands ###
