"""add blocos personalizados e anexos

Revision ID: 65a9b35c2eb8
Revises: 655b50076318
Create Date: 2026-06-13 16:29:20.111889

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65a9b35c2eb8'
down_revision = '655b50076318'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
