"""initial schema

Revision ID: 68f3cc569fbd
Revises: 
Create Date: 2026-05-23 19:28:03.391090

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68f3cc569fbd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_acao'), ['acao'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_criado_em'), ['criado_em'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_entidade_tipo'), ['entidade_tipo'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_projeto_id'), ['projeto_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_usuario_id'), ['usuario_id'], unique=False)

    with op.batch_alter_table('requisitos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_requisitos_autor_id'), ['autor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_requisitos_projeto_id'), ['projeto_id'], unique=False)

    with op.batch_alter_table('validacoes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_validacoes_requisito_id'), ['requisito_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_validacoes_validador_id'), ['validador_id'], unique=False)
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'requisitos', ['requisito_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('validacoes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'requisitos', ['requisito_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_validacoes_validador_id'))
        batch_op.drop_index(batch_op.f('ix_validacoes_requisito_id'))

    with op.batch_alter_table('requisitos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_requisitos_projeto_id'))
        batch_op.drop_index(batch_op.f('ix_requisitos_autor_id'))

    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_usuario_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_projeto_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_entidade_tipo'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_criado_em'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_acao'))

    # ### end Alembic commands ###
