"""add convites_projeto e membros_projeto

Revision ID: 6d583dbd0a21
Revises: 65a9b35c2eb8
Create Date: 2026-06-13 16:56:47.687759

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d583dbd0a21'
down_revision = '65a9b35c2eb8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('convites_projeto',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('projeto_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('perfil', sa.String(length=20), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('convidado_por_id', sa.Integer(), nullable=False),
    sa.Column('aceito_por_id', sa.Integer(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('expira_em', sa.DateTime(), nullable=False),
    sa.CheckConstraint("perfil IN ('cliente', 'desenvolvedor')", name='ck_convites_perfil'),
    sa.CheckConstraint("status IN ('pendente', 'aceito', 'cancelado')", name='ck_convites_status'),
    sa.ForeignKeyConstraint(['aceito_por_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['convidado_por_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['projeto_id'], ['projetos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    with op.batch_alter_table('convites_projeto', schema=None) as batch_op:
        batch_op.create_index('ix_convites_projeto', ['projeto_id', 'status'], unique=False)
        batch_op.create_index('ix_convites_token', ['token'], unique=True)

    op.create_table('membros_projeto',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('projeto_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('adicionado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['projeto_id'], ['projetos.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('projeto_id', 'usuario_id', name='uq_membro_projeto')
    )
    with op.batch_alter_table('membros_projeto', schema=None) as batch_op:
        batch_op.create_index('ix_membros_usuario', ['usuario_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('membros_projeto', schema=None) as batch_op:
        batch_op.drop_index('ix_membros_usuario')

    op.drop_table('membros_projeto')
    with op.batch_alter_table('convites_projeto', schema=None) as batch_op:
        batch_op.drop_index('ix_convites_token')
        batch_op.drop_index('ix_convites_projeto')

    op.drop_table('convites_projeto')
    # ### end Alembic commands ###
