"""add projeto_visao_geral

Revision ID: 9a5e280eac81
Revises: 88a37c041bb4
Create Date: 2026-06-15 17:26:54.042344

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a5e280eac81'
down_revision = '88a37c041bb4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projeto_visao_geral',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('projeto_id', sa.Integer(), nullable=False),
    sa.Column('o_que', sa.Text(), nullable=True),
    sa.Column('por_que', sa.Text(), nullable=True),
    sa.Column('quem', sa.Text(), nullable=True),
    sa.Column('onde', sa.Text(), nullable=True),
    sa.Column('quando', sa.Text(), nullable=True),
    sa.Column('como', sa.Text(), nullable=True),
    sa.Column('quanto', sa.Text(), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['projeto_id'], ['projetos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('projeto_visao_geral', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_projeto_visao_geral_projeto_id'), ['projeto_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projeto_visao_geral', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_projeto_visao_geral_projeto_id'))

    op.drop_table('projeto_visao_geral')
    # ### end Alembic commands ###
