"""add_unique_constraints_and_composite_indexes

Revision ID: b87ffa33f168
Revises: 37c98cc99bfc
Create Date: 2026-05-28 14:32:58.568481

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b87ffa33f168'
down_revision = '37c98cc99bfc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_entidade_tipo'))
        batch_op.create_index('ix_audit_entity', ['entidade_tipo', 'entidade_id'], unique=False)

    with op.batch_alter_table('projetos', schema=None) as batch_op:
        batch_op.create_index('ix_projetos_gestor_ativo', ['gestor_id', 'ativo'], unique=False)

    with op.batch_alter_table('requisitos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_requisitos_codigo'))
        batch_op.create_index('ix_requisitos_projeto_ativo', ['projeto_id', 'ativo'], unique=False)
        batch_op.create_unique_constraint('uq_requisito_projeto_codigo', ['projeto_id', 'codigo'])

    with op.batch_alter_table('validacoes', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_validacao_requisito_validador', ['requisito_id', 'validador_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('validacoes', schema=None) as batch_op:
        batch_op.drop_constraint('uq_validacao_requisito_validador', type_='unique')

    with op.batch_alter_table('requisitos', schema=None) as batch_op:
        batch_op.drop_constraint('uq_requisito_projeto_codigo', type_='unique')
        batch_op.drop_index('ix_requisitos_projeto_ativo')
        batch_op.create_index(batch_op.f('ix_requisitos_codigo'), ['codigo'], unique=False)

    with op.batch_alter_table('projetos', schema=None) as batch_op:
        batch_op.drop_index('ix_projetos_gestor_ativo')

    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index('ix_audit_entity')
        batch_op.create_index(batch_op.f('ix_audit_logs_entidade_tipo'), ['entidade_tipo'], unique=False)

    # ### end Alembic commands ###
