"""add diagramas table

Revision ID: d196b0c7c507
Revises: f4a5b6c7d8e9
Create Date: 2026-06-13 15:57:33.339484

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd196b0c7c507'
down_revision = 'f4a5b6c7d8e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('diagramas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('projeto_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('tipo_mime', sa.String(length=100), nullable=False),
    sa.Column('dados', sa.LargeBinary(), nullable=False),
    sa.Column('tamanho', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['projeto_id'], ['projetos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('diagramas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_diagramas_projeto_id'), ['projeto_id'], unique=False)

    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index('ix_audit_project_created', ['projeto_id', 'criado_em'], unique=False)

    with op.batch_alter_table('password_reset_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_prt_token_hash'))
        batch_op.drop_index(batch_op.f('ix_prt_usuario_id'))
        batch_op.create_index(batch_op.f('ix_password_reset_tokens_token_hash'), ['token_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_password_reset_tokens_usuario_id'), ['usuario_id'], unique=False)

    with op.batch_alter_table('requisitos', schema=None) as batch_op:
        batch_op.alter_column('codigo',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)

    with op.batch_alter_table('token_blocklist', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))

    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usuarios_email'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usuarios_email'), ['email'], unique=False)

    with op.batch_alter_table('token_blocklist', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))

    with op.batch_alter_table('requisitos', schema=None) as batch_op:
        batch_op.alter_column('codigo',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)

    with op.batch_alter_table('password_reset_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_password_reset_tokens_usuario_id'))
        batch_op.drop_index(batch_op.f('ix_password_reset_tokens_token_hash'))
        batch_op.create_index(batch_op.f('ix_prt_usuario_id'), ['usuario_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_prt_token_hash'), ['token_hash'], unique=False)

    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index('ix_audit_project_created')

    with op.batch_alter_table('diagramas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_diagramas_projeto_id'))

    op.drop_table('diagramas')
    # ### end Alembic commands ###
